import React, { useMemo } from 'react';
import { Download, TrendingUp, DollarSign, Package, ArrowDownToLine, ReceiptText, Lock, Calculator, Coins, FileText } from 'lucide-react';
import { Product, Sale, PlanType, Language, CurrencyCode } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatMoney, CURRENCIES } from '../App';

interface ReportsViewProps {
  products: Product[];
  sales: Sale[];
  plan: PlanType;
  lang: Language;
  currency: CurrencyCode;
  companyName: string;
  userName: string;
  onLogActivity: (action: string, details: string) => void;
}

const translations: Record<Language, any> = {
  en: {
    title: "Stock Out Income Report",
    subtitle: "Complete financial audit and margin tracking",
    download_btn: "Download PDF Report",
    rev_dist: "Income Distribution",
    summary: "EXECUTIVE SUMMARY",
    audit_log: "Stock Out Income Report",
    col_no: "No",
    col_name: "Product Name",
    col_code: "Product Code",
    col_qty: "Qty",
    col_price: "Price",
    col_sold_amt: "Total Sold",
    col_interest: "Profit",
    col_total_inc: "Final Inc.",
    col_date: "Date",
    gen_by: "Generated By",
    gen_on: "Generated on",
    period: "Report Period",
    total_products_sold: "Total Products Sold",
    total_qty: "Total Stock Out Quantity",
    total_sales_amt: "Total Sales Amount",
    total_interest: "Total Interest Earned",
    final_income: "Final Total Income",
    footer_note: "This report was automatically generated by StockMaster.",
    currency_note: "All amounts are in {currency}.",
    support_note: "For support, contact support@stockmaster.app"
  },
  rw: {
    title: "Raporo y'Injyana n'Inyungu",
    subtitle: "Igenzurwa ry'imari n'inyungu",
    download_btn: "Kura raporo muri PDF",
    rev_dist: "Ikwirakwizwa ry'Injyana",
    summary: "INCAMAKE YA RAPORO",
    audit_log: "Raporo y'Injyana n'Inyungu",
    col_no: "Nimero",
    col_name: "Igicuruzwa",
    col_code: "Kode",
    col_qty: "Umubare",
    col_price: "Igiciro",
    col_sold_amt: "Ayagurishijwe",
    col_interest: "Inyungu",
    col_total_inc: "Igiteranyo",
    col_date: "Itariki",
    gen_by: "Yakozwe na",
    gen_on: "Yakozwe ku",
    period: "Igihe",
    total_products_sold: "Ibicuruzwa byagurishijwe",
    total_qty: "Ingano yose yasohotse",
    total_sales_amt: "Amafaranga yose yasohotse",
    total_interest: "Inyungu yose yabonetse",
    final_income: "Injyana yose hamwe",
    footer_note: "Iyi raporo yakozwe na StockMaster mu buryo bwikora.",
    currency_note: "Imibare yose iri mu {currency}.",
    support_note: "Ubufasha: support@stockmaster.app"
  },
  fr: {
    title: "Rapport des Sorties et Revenus",
    subtitle: "Audit financier complet et suivi des marges",
    download_btn: "Télécharger le Rapport PDF",
    rev_dist: "Répartition des Revenus",
    summary: "RÉSUMÉ EXÉCUTIF",
    audit_log: "Rapport des Sorties et Revenus",
    col_no: "N°",
    col_name: "Nom de l'Article",
    col_code: "Code Article",
    col_qty: "Qté",
    col_price: "Prix Unitaire",
    col_sold_amt: "Total Vendu",
    col_interest: "Intérêt",
    col_total_inc: "Revenu Total",
    col_date: "Date",
    gen_by: "Généré par",
    gen_on: "Généré le",
    period: "Période du Rapport",
    total_products_sold: "Total Articles Vendus",
    total_qty: "Quantité Totale Sortie",
    total_sales_amt: "Montant Total des Ventes",
    total_interest: "Total Intérêts Gagnés",
    final_income: "Revenu Total Final",
    footer_note: "Ce rapport a été généré automatiquement par StockMaster.",
    currency_note: "Tous les montants sont en {currency}.",
    support_note: "Support: support@stockmaster.app"
  }
};

const ReportsView: React.FC<ReportsViewProps> = ({ products, sales, plan, lang, currency, companyName, userName, onLogActivity }) => {
  const t = (key: string) => translations[lang][key] || key;
  const currencySymbol = CURRENCIES[currency].symbol;
  const currencyName = CURRENCIES[currency].name;
  
  const stats = useMemo(() => {
    let totalProductsSold = new Set(sales.map(s => s.productId)).size;
    let totalStockOutQty = sales.reduce((acc, s) => acc + s.quantity, 0);
    let totalSalesAmount = sales.reduce((acc, s) => acc + s.totalAmount, 0);
    
    let totalInterestEarned = sales.reduce((acc, s) => {
      const product = products.find(p => p.id === s.productId);
      const cost = product ? product.costPrice * s.quantity : 0;
      return acc + (s.totalAmount - cost);
    }, 0);

    let finalTotalIncome = totalSalesAmount + totalInterestEarned;
    
    const productSalesMap: Record<string, number> = {};
    sales.forEach(s => {
      productSalesMap[s.productName] = (productSalesMap[s.productName] || 0) + s.totalAmount;
    });
    
    const topProducts = Object.entries(productSalesMap)
      .map(([name, total]) => ({ name, total }))
      .sort((a, b) => b.total - a.total)
      .slice(0, 5);

    let dateRange = "All History";
    if (sales.length > 0) {
      const dates = sales.map(s => new Date(s.timestamp).getTime());
      const minDate = new Date(Math.min(...dates)).toLocaleDateString('en-GB');
      const maxDate = new Date(Math.max(...dates)).toLocaleDateString('en-GB');
      dateRange = `${minDate} – ${maxDate}`;
    }

    return { 
      totalProductsSold, 
      totalStockOutQty, 
      totalSalesAmount, 
      totalInterestEarned, 
      finalTotalIncome, 
      topProducts, 
      dateRange 
    };
  }, [products, sales]);

  const COLORS = ['#6366f1', '#8b5cf6', '#a855f7', '#d946ef', '#ec4899'];

  const handleDownloadPDF = () => {
    if (plan !== 'pro') {
      alert("Professional PDF Reports are exclusive to Business Pro plan.");
      return;
    }

    const doc = new jsPDF('p', 'mm', 'a4'); 
    const timestamp = new Date();
    const fileDate = timestamp.toISOString().split('T')[0];
    const displayTime = timestamp.toLocaleString('en-GB', { hour: '2-digit', minute: '2-digit' });
    const displayDate = timestamp.toLocaleDateString('en-GB');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // 1. Report Header
    doc.setFillColor(82, 82, 242);
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("STOCKMASTER", 15, 20);
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Business Intelligence Engine", 15, 28);
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(t('audit_log').toUpperCase(), pageWidth - 15, 20, { align: 'right' });
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(companyName, pageWidth - 15, 28, { align: 'right' });

    // Meta Header Info
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(9);
    doc.text(`${t('period')}: ${stats.dateRange}`, 15, 52);
    doc.text(`${t('gen_on')}: ${displayDate} – ${displayTime}`, 15, 57);
    doc.text(`${t('gen_by')}: ${userName}`, 15, 62);

    // 2. Summary Section Box
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(15, 70, pageWidth - 30, 35, 3, 3, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(15, 70, pageWidth - 30, 35, 3, 3, 'S');

    doc.setTextColor(82, 82, 242);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(t('summary'), 20, 78);

    doc.setTextColor(51, 65, 85);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    
    doc.text(`• ${t('total_products_sold')}: ${stats.totalProductsSold}`, 20, 85);
    doc.text(`• ${t('total_qty')}: ${stats.totalStockOutQty.toLocaleString()}`, 20, 92);
    
    doc.text(`• ${t('total_sales_amt')}: ${formatMoney(stats.totalSalesAmount, currency)}`, 100, 85);
    doc.text(`• ${t('total_interest')}: ${formatMoney(stats.totalInterestEarned, currency)}`, 100, 92);
    
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129);
    doc.text(`• ${t('final_income')}: ${formatMoney(stats.finalTotalIncome, currency)}`, 20, 99);

    // 3. Stock Out Data Table
    const tableHeaders = [[
      t('col_no'), 
      t('col_name'), 
      t('col_code'), 
      t('col_qty'), 
      `${t('col_price')} (${currencySymbol})`, 
      `${t('col_sold_amt')} (${currencySymbol})`,
      `${t('col_interest')} (${currencySymbol})`,
      `${t('col_total_inc')} (${currencySymbol})`,
      t('col_date')
    ]];

    const tableData = sales.map((sale, index) => {
      const product = products.find(p => p.id === sale.productId);
      const cost = product ? product.costPrice * sale.quantity : 0;
      const interest = sale.totalAmount - cost;
      const totalIncome = sale.totalAmount + interest;

      return [
        index + 1,
        sale.productName,
        product?.sku || 'N/A',
        sale.quantity.toLocaleString(),
        sale.unitPrice.toLocaleString(),
        sale.totalAmount.toLocaleString(),
        interest.toLocaleString(),
        totalIncome.toLocaleString(),
        new Date(sale.timestamp).toLocaleDateString('en-GB')
      ];
    });

    // Calculate totals for table footer
    const footerRow = [
      '',
      'TOTALS',
      '',
      stats.totalStockOutQty.toLocaleString(),
      '',
      stats.totalSalesAmount.toLocaleString(),
      stats.totalInterestEarned.toLocaleString(),
      stats.finalTotalIncome.toLocaleString(),
      ''
    ];

    autoTable(doc, {
      startY: 110,
      head: tableHeaders,
      body: tableData,
      foot: [footerRow],
      showFoot: 'lastPage',
      theme: 'grid',
      headStyles: { 
        fillColor: [82, 82, 242], 
        textColor: [255, 255, 255],
        fontSize: 7,
        fontStyle: 'bold',
        halign: 'center'
      },
      footStyles: {
        fillColor: [241, 245, 249],
        textColor: [51, 65, 85],
        fontSize: 7,
        fontStyle: 'bold',
        halign: 'right'
      },
      styles: {
        fontSize: 7,
        cellPadding: 2
      },
      columnStyles: {
        0: { halign: 'center', cellWidth: 8 },
        2: { halign: 'center', cellWidth: 15 },
        3: { halign: 'center', cellWidth: 12 },
        4: { halign: 'right' },
        5: { halign: 'right' },
        6: { halign: 'right' },
        7: { halign: 'right', fontStyle: 'bold' },
        8: { halign: 'center', cellWidth: 20 }
      },
      margin: { top: 15, left: 15, right: 15 }
    });

    // 4. Page numbering footer (removed system branding words as requested)
    const pageCount = (doc as any).internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(148, 163, 184);
      doc.setFont("helvetica", "italic");
      
      const bottomY = pageHeight - 10;
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 15, bottomY, { align: 'right' });
      doc.text(companyName, 15, bottomY);
    }

    const fileName = `stockmaster-report-${fileDate}.pdf`;
    doc.save(fileName);
    onLogActivity("Report Exported", `Generated Stock Out Income Report PDF.`);
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500 pb-12 text-left">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h3 className="text-slate-800 font-black text-2xl tracking-tight uppercase italic">{t('title')}</h3>
          <p className="text-sm text-slate-500 font-medium">{t('subtitle')}</p>
        </div>
        <button 
          onClick={handleDownloadPDF}
          className={`flex items-center gap-3 px-8 py-4 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all shadow-xl ${plan === 'pro' ? 'bg-slate-900 text-white hover:bg-black active:scale-95' : 'bg-slate-100 text-slate-400 cursor-not-allowed'}`}
        >
          {plan === 'pro' ? <FileText size={18} /> : <Lock size={18} />}
          {t('download_btn')}
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
         <ReportSummaryCard label={t('total_sales_amt')} value={formatMoney(stats.totalSalesAmount, currency)} icon={<Coins size={20} />} color="text-indigo-600" bgColor="bg-indigo-50" />
         <ReportSummaryCard label={t('total_interest')} value={formatMoney(stats.totalInterestEarned, currency)} icon={<Calculator size={20} />} color="text-amber-600" bgColor="bg-amber-50" />
         <div className="bg-slate-900 text-white p-10 rounded-[48px] border border-white/5 shadow-2xl relative overflow-hidden flex flex-col justify-center">
            <h4 className="text-indigo-400 text-[9px] font-black uppercase tracking-[0.3em] mb-3 leading-none italic">{t('final_income')}</h4>
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-black tracking-tighter">{formatMoney(stats.finalTotalIncome, currency)}</span>
            </div>
            <TrendingUp className="absolute -right-6 -bottom-6 text-white/5" size={160} strokeWidth={3} />
         </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-10">
        <div className="lg:col-span-2 bg-white p-12 rounded-[48px] border border-slate-200 shadow-sm overflow-hidden flex flex-col">
          <div className="flex items-center gap-3 mb-12">
            <div className="w-10 h-10 bg-indigo-50 text-indigo-600 rounded-xl flex items-center justify-center shadow-inner"><ReceiptText size={20} /></div>
            <h4 className="font-black text-slate-800 uppercase tracking-widest text-[11px]">{t('rev_dist')}</h4>
          </div>
          <div className="h-[400px] flex-1">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={stats.topProducts} layout="vertical">
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis type="number" hide />
                <YAxis dataKey="name" type="category" width={150} axisLine={false} tickLine={false} tick={{fontSize: 10, fill: '#64748b', fontWeight: 800}} />
                <Bar dataKey="total" radius={[0, 12, 12, 0]} barSize={40}>
                  {stats.topProducts.map((_, index) => <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />)}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white p-12 rounded-[48px] border border-slate-200 shadow-sm flex flex-col justify-center text-center">
            <div className="w-20 h-20 bg-indigo-50 text-indigo-600 rounded-[28px] flex items-center justify-center mx-auto mb-8 shadow-inner">
               <Package size={40} />
            </div>
            <h4 className="text-slate-400 text-[10px] font-black uppercase tracking-[0.4em] mb-4">{t('total_qty')}</h4>
            <div className="flex items-center justify-center gap-3">
              <span className="text-6xl font-black text-slate-900 tracking-tighter">{stats.totalStockOutQty.toLocaleString()}</span>
              <div className="bg-slate-100 px-3 py-1.5 rounded-full text-[9px] font-black text-slate-500 uppercase tracking-widest">Units</div>
            </div>
            <p className="text-xs text-slate-400 font-bold mt-8 italic leading-relaxed">
              Total volume detected across {stats.totalProductsSold} unique product identities within the report timeframe. {t('currency_note').replace('{currency}', currencyName)}
            </p>
        </div>
      </div>
    </div>
  );
};

const ReportSummaryCard = ({ label, value, icon, color, bgColor }: any) => (
  <div className="bg-white p-10 rounded-[48px] border border-slate-200 shadow-sm flex flex-col justify-center">
    <div className="flex items-center justify-between mb-8">
       <h4 className="text-slate-400 text-[9px] font-black uppercase tracking-[0.3em] leading-none">{label}</h4>
       <div className={`${bgColor} ${color} p-3 rounded-2xl shadow-inner`}>{icon}</div>
    </div>
    <p className="text-3xl font-black text-slate-900 tracking-tighter truncate">{value}</p>
  </div>
);

export default ReportsView;